name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-libssh:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://git.libssh.org/projects/libssh.git libssh

  build:
    needs: build-libssh
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libssh-dev
    - name: make
      run: make
    - name: make tests
      run: make tests
