name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build libssh from Git
      run: |
          git clone --depth 1 --branch libssh-0.9.5 https://git.libssh.org/projects/libssh.git libssh
          mkdir libssh-build
          cd libssh-build
          cmake ../libssh
          sudo make install
#    - name: Install dependencies
#      run: sudo apt-get install libssh-dev
    - name: make
      run: make
    - name: make tests
      run: make tests
